# TODO: Add description

base: !!str "http://golem.fjfi.cvut.cz/shotdir/"

plasma_presence: !!str "/Diagnostics/PlasmaDetection/Results/b_plasma"

t_plasma_start: !!str "/Diagnostics/PlasmaDetection/Results/t_plasma_start"
t_plasma_end: !!str "/Diagnostics/PlasmaDetection/Results/t_plasma_end"

# TODO: Find exact shot number when the data structure changed
MHDring_data_0-46999: !!str "/Diagnostics/MHDring-TM/DAS_raw_data_dir/NI.lvm"
MHDring_data_47000-now: !!str "/Diagnostics/MHDring-TM/DAS_raw_data_dir/rawData.csv"
